module.exports = {
    "Deloitte": {
        "synonyms": [
            "deloitte",
            "deloitte sa",
            "deloitte ag"
        ],
        "longText": "# Deloitte\n Deloitte Touche Tohmatsu Limited, commonly referred to as Deloitte, is a UK-incorporated multinational professional services firm with operational headquarters in New York City in the United States.\n Deloitte is one of the 'Big Four' accounting firms and the largest professional services network in the world by revenue and number of professionals. Deloitte provides audit, tax, consulting, enterprise risk and financial advisory services with more than 263,900 professionals globally. In FY 2017, the company earned a record $38.8 billion USD in revenues. As of 2016, Deloitte is the 6th-largest privately owned organization in the United States.\n As per reports in 2012, Deloitte had the largest number of clients amongst FTSE 250 companies in the UK and in 2015, Deloitte currently has the highest market share in auditing among the top 500 companies in India. Deloitte has been ranked number one by market share in consulting by Gartner, and for the fourth consecutive year, Kennedy Consulting Research and Advisory ranks Deloitte number one in both global consulting and management consulting based on aggregate revenue.",
        "cards": [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Deloitte.svg/920px-Deloitte.svg.png"
        ]
    },
    "EY": {
        "synonyms": [
            "ernst and young",
            "e&y",
            "ernst & young"
        ],
        "longText": "# EY\n EY (formerly Ernst & Young) is a multinational professional services firm headquartered in London, England. EY is one of the largest professional services firms in the world and is one of the 'Big Four' accounting firms.\n EY operates as a network of member firms which are separate legal entities in individual countries. It has 231,000 employees in over 700 offices around 150 countries in the world. It provides assurance (including financial audit), tax, consulting and advisory services to companies.",
        "cards": [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/EY_Logo_Beam_Tag_Stacked_RGB_EN.png/150px-EY_Logo_Beam_Tag_Stacked_RGB_EN.png"
        ]
    },
    "KPMG": {
        "synonyms": [
            "kpmg sa",
            "kpmg ag"
        ],
        "longText": "# KPMG\n KPMG is a professional service company and one of the Big Four auditors, along with Deloitte, Ernst & Young (EY), and PricewaterhouseCoopers (PwC). Seated in Amstelveen, the Netherlands, KPMG employs 189,000 people and has three lines of services: financial audit, tax, and advisory. Its tax and advisory services are further divided into various service groups.\n The name KPMG stands for 'Klynveld Peat Marwick Goerdeler.' It was chosen when KMG (Klynveld Main Goerdeler) merged with Peat Marwick in 1987.",
        "cards": [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/KPMG.svg/709px-KPMG.svg.png"
        ]
    },
    "PWC": {
        "synonyms": [
            "price",
            "pricewhaterhousecoopers"
        ],
        "longText": "# PwC\n PricewaterhouseCoopers (doing business as PwC) is a multinational professional services network headquartered in London, United Kingdom. It is the second largest professional services firm in the world, and is one of the Big Four auditors, along with Deloitte, EY and KPMG. Vault Accounting 50 has ranked PwC as the most prestigious accounting firm in the world for seven consecutive years, as well as the top firm to work for in North America for three consecutive years. \n PwC is a network of firms in 157 countries, 743 locations, with 223,468 people. As of 2015, 22% of the workforce worked in Asia, 26% in North America and Caribbean and 32% in Western Europe. The company's global revenues were $37.7 billion in FY 2017, of which $16 billion was generated by its Assurance practice, $9.46 billion by its Tax practice and $12.25 billion by its Advisory practice. PwC provides services to 422 out of 500 Fortune 500 companies.",
        "cards": [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/PricewaterhouseCoopers_Logo.svg/220px-PricewaterhouseCoopers_Logo.svg.png"
        ]
    }

}