module.exports = {
    "Deloitte": {
        "synonyms": [
            "deloitte",
            "deloitte sa",
            "deloitte ag"
        ],
        "longText": "# Deloitte\n Deloitte Touche Tohmatsu Limited, commonly referred to as Deloitte, is a UK-incorporated multinational professional services firm with operational headquarters in New York City in the United States.\n Deloitte is one of the 'Big Four' accounting firms and the largest professional services network in the world by revenue and number of professionals. Deloitte provides audit, tax, consulting, enterprise risk and financial advisory services with more than 263,900 professionals globally. In FY 2017, the company earned a record $38.8 billion USD in revenues. As of 2016, Deloitte is the 6th-largest privately owned organization in the United States.\n As per reports in 2012, Deloitte had the largest number of clients amongst FTSE 250 companies in the UK and in 2015, Deloitte currently has the highest market share in auditing among the top 500 companies in India. Deloitte has been ranked number one by market share in consulting by Gartner, and for the fourth consecutive year, Kennedy Consulting Research and Advisory ranks Deloitte number one in both global consulting and management consulting based on aggregate revenue.",
        "cards": [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Deloitte.svg/920px-Deloitte.svg.png"
        ]
    },
    "PWC": {
        "synonyms": [
            "price",
            "pricewhaterhousecoopers"       
	],
        "longText": "PricewaterhouseCoopers (doing business as PwC) is a multinational professional services network headquartered in London, United Kingdom. It is the second largest professional services firm in the world, and is one of the Big Four auditors, along with Deloitte, EY and KPMG. Vault Accounting 50 has ranked PwC as the most prestigious accounting firm in the world for seven consecutive years, as well as the top firm to work for in North America for three consecutive years. \n PwC is a network of firms in 157 countries, 743 locations, with 223,468 people. As of 2015, 22% of the workforce worked in Asia, 26% in North America and Caribbean and 32% in Western Europe. The company's global revenues were $37.7 billion in FY 2017, of which $16 billion was generated by its Assurance practice, $9.46 billion by its Tax practice and $12.25 billion by its Advisory practice. PwC provides services to 422 out of 500 Fortune 500 companies.",
        "cards": [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/PricewaterhouseCoopers_Logo.svg/220px-PricewaterhouseCoopers_Logo.svg.png"
        ]
    }

}
